# -*- coding: utf-8 -*-
"""Copy of Preprocess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Urg93V6SGKqBIlqjsmYye78q6kw_RgGc
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
k=pd.read_csv('/content/drive/My Drive/Colab Notebooks/dataset/azedf.zip (Unzipped Files)/train_0_0.csv')

sample=k

new=sample[['ip','app','os','channel','click_time','attributed_time','is_attributed']]
new=new.sort_values(by=['ip'],ascending=True)

import random
from ipaddress import IPv4Address


def ipecg(seed):
    random.seed(seed)
    return str(IPv4Address(random.getrandbits(32)))

import random
k=[]
for i in new['ip']:
  j=random.randint(2,999)
  rev=ipecg(i+j)
  k.append(rev)
new['valid']=k
new

new.to_excel("output1.xlsx")

