# -*- coding: utf-8 -*-
"""Geolookup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LF31sc18pzQGlirHHjydFFDt1Pj6VFEI
"""

pip install ipstack

from google.colab import drive
drive.mount('/content/drive')

from ipstack import GeoLookup
def orient(ip):
  #geo_lookup = GeoLookup("431c444c2d03ca049a4356d7d7c897b7")
  geo_lookup = GeoLookup("f02b34fc34b84c40be72c2299657cef0")
  location = geo_lookup.get_location(ip)
  return(location)

import pandas as pd
file='/content/drive/My Drive/Colab Notebooks/dataset/output/train_'+str(0)+'_'+str(0)+'.csv'
t=pd.read_csv(file).head(200)

lat=[]
long=[]
for a in t['valid']:
  data=orient(a)
  lat.append(data['latitude'])
  long.append(data['longitude'])  
t['latitude']=lat
t['longitde']=long

t.to_excel("sample integration.xlsx")

t

from ipstack import GeoLookup
geo_lookup = GpeoLookup("431c444c2d03ca049a4356d7d7c897b7")
location = geo_lookup.get_location("215.102.113.3")

k=location

k['latitude']
k['longitude']

