# -*- coding: utf-8 -*-
"""UPDATER

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iob1tp6ZqOOEEv40FUGoFuIfAyxPHC5M
"""

from google.colab import drive
drive.mount('/content/drive')

import random
from ipaddress import IPv4Address


def ipecg(seed):
    random.seed(seed)
    return str(IPv4Address(random.getrandbits(32)))

import pandas as pd
import random
for i in range(4,5):
    for j in range(10,11):
        file='/content/drive/My Drive/Colab Notebooks/dataset/azedf.zip (Unzipped Files)/train_'+str(i)+'_'+str(j)+'.csv'
        k=pd.read_csv(file,names=['ip','app','device','os','channel','click_time','attributed_time','is_attributed'])
        sample=k
        new=sample[['ip','app','os','channel','click_time','is_attributed']]
        new=new.sort_values(by=['ip'],ascending=True)
        
        p=[]
        
        
        for a in new['ip']:
          b=random.randint(2,999)
          rev=ipecg(a+b)
          p.append(rev)
        new['valid']=p
        new.to_csv('/content/drive/My Drive/Colab Notebooks/dataset/output/train_'+str(i)+'_'+str(j)+'.csv',index=False,header=False)

new

